# Generated by Django 4.2.5 on 2024-08-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_title', models.CharField(default='', max_length=20)),
                ('Batch_Capacity', models.CharField(max_length=20)),
                ('Time_from', models.CharField(max_length=20)),
                ('Time_to', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=6)),
                ('sex', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=6)),
                ('qualification', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.CharField(default='1234', max_length=20)),
                ('experience', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
