from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('', views.loginn),
    path('addbatch/',views.addbatch),
    path('updatebatch/<id>',views.updatebatch),
    path('updatebatch_post/<id>',views.updatebatch_post),
    path('deletebatch/<id>',views.deletebatch),
    path('updatetrainer/<id>',views.updatetrainer),
    path('updatetrainer_post/<id>',views.updatetrainer_post),
    path('adminhome', views.adminhome),
    path('addtrainer', views.addtrainer),
    path('edittrainer/<id>',views.updatetraineradmin),
    path('edittrainer_post/<id>',views.updatetraineradmin_post),
    path('deletetrainer/<id>',views.deletetrainer),
    path('assigntrainer/<id>', views.assigntrainer),
    path('assignbatch_post/<id>', views.assignbatch_post),
    path('login_post', views.login_post),
    path('viewtrainer',views.viewtrainer),
    path('viewbatch', views.viewbatch),
    path('addbatch_post', views.addbatch_post),
    path('addtrainer_post', views.addtrainer_post),
    path('viewfeedback', views.viewfeedback),
    path('viewrequest/<id>', views.viewrequest),
    path('rejectrequest/<id>',views.rejectrequest),
    path('deleterequest/<id>',views.deleterequest),
    path('viewbatchtrainer/<id>',views.viewbatchtrainer),
    path('viewprofile/',views.viewprofile),
    path('trainerhome/',views.trainerhome),
    path('register',views.register),
    path('register_post',views.register_post),
    path('userhome/',views.userhome),
    path('uploadhealth/',views.uploadhealth),
    path('forgot_pass',views.forgot_pass),
    path('forgot_pass_post',views.forgot_pass_post),
    path('updateuser/<id>',views.updateuser),
    path('updateuser_post/<id>',views.updateuser_post),
    path('viewuserprofile',views.viewuserprofile),
    path('sendfeedback_post/',views.sendfeedback_post),
    path('sendfeedback/',views.sendfeedback),
    path('viewbatchuser/',views.viewbatchuser),
    path('calculate_bmi/', views.calculate_bmi),
    path('sendrequest/<id>/<jid>',views.sendrequest),
    path('uploadhealthpost/',views.uploadhealth_post),
    path('viewhealth/',views.viewhealth),
    path('updatehealth/<id>',views.updatehealth),
    path('updatehealth_post/<id>',views.updatehealth_post),
    path('mybatch/',views.mybatch),
]