from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('', views.loginn),
    path('addbatch/',views.addbatch),
    path('updatebatch/<id>',views.updatebatch),
    path('updatebatch_post/<id>',views.updatebatch_post),
    path('deletebatch/<id>',views.deletebatch),
    path('updatetrainer/<id>',views.updatetrainer),
    path('updatetrainer_post/<id>',views.updatetrainer_post),
    path('adminhome', views.adminhome),
    path('addtrainer', views.addtrainer),
    path('edittrainer/<id>',views.updatetraineradmin),
    path('edittrainer_post/<id>',views.updatetraineradmin_post),
    path('deletetrainer/<id>',views.deletetrainer),
    path('assigntrainer/<id>', views.assigntrainer),
    path('assignbatch_post/<id>', views.assignbatch_post),
    path('login_post', views.login_post),
    path('viewtrainer',views.viewtrainer),
    path('viewbatch', views.viewbatch),
    path('addbatch_post', views.addbatch_post),
    path('addtrainer_post', views.addtrainer_post),
    path('viewfeedback', views.viewfeedback),
    path('viewrequest/<id>', views.viewrequest),
    path('rejectrequest/<id>',views.rejectrequest),
    path('deleterequest/<id>',views.deleterequest),
    path('viewbatchtrainer/<id>',views.viewbatchtrainer),
    path('viewprofile/',views.viewprofile),
    path('trainerhome/',views.trainerhome),
    path('uploaddietplan/<id>/<uid>',views.uploaddietplan),
    path('uploaddietplan_post/<id>/<uid>',views.uploaddietplan_post),
    path('viewdietplan/<uid>',views.viewdietplan),
    path('editdietplan/<id>',views.editdietplan),
    path('editdietplan_post/<id>',views.editdietplan_post),
    path('deletedietplan/<id>',views.deletedietplan),
    path('viewassignedbatch/',views.viewassignedbatch),
    path('viewmembers/<id>',views.viewmembers),
    path('viewbatchmember/<id>',views.viewbatchmember),
    path('viewhealthinfo/<id>',views.viewhealthinfo),
    path('register',views.register),
    path('register_post',views.register_post),
    path('userhome/',views.userhome),
    path('uploadhealth/',views.uploadhealth),
    path('addtips/<uid>',views.addtips),
    path('addworkout/<uid>',views.addworkout),
    path('viewtips/<uid>',views.viewtips),
    path('viewworkout/<uid>',views.viewworkout),
    path('addtips_post/<uid>',views.addtips_post),
    path('addworkout_post/<uid>',views.addworkout_post),
    path('edittip/<id>',views.edittip),
    path('edittip_post/<id>',views.edittip_post),
    path('deletetip/<id>',views.deletetip),
    path('editworkout/<id>',views.editworkout),
    path('editworkout_post/<id>',views.editworkout_post),
    path('deleteworkout/<id>',views.deleteworkout),
    path('forgot_pass',views.forgot_pass),
    path('forgot_pass_post',views.forgot_pass_post),
    path('updateuser/<id>',views.updateuser),
    path('updateuser_post/<id>',views.updateuser_post),
    path('viewuserprofile',views.viewuserprofile),
    path('viewtipsuser/',views.viewtipsuser),
    path('viewworkoutuser/',views.viewworkoutuser),
    path('sendfeedback_post/',views.sendfeedback_post),
    path('sendfeedback/',views.sendfeedback),
    path('viewbatchuser/',views.viewbatchuser),
    path('viewdietplanuser/',views.viewdietplanuser),
    path('user_exit_batch/<id>',views.user_exit_batch),
    path('calculate_bmi/', views.calculate_bmi),
    path('sendrequest/<id>/<jid>',views.sendrequest),
    path('uploadhealthpost/',views.uploadhealth_post),
    path('viewhealth/',views.viewhealth),
    path('updatehealth/<id>',views.updatehealth),
    path('updatehealth_post/<id>',views.updatehealth_post),
    path('mybatch/',views.mybatch),
    path('chattrainer/<id>',views.chattrainer),
    path('chatuser/<id>',views.chatuser),
    path('chatsent',views.chatsnd),
    path('Uchatsent',views.Uchatsent),
    path('chatreply',views.chatrply),
    path('Uchatreply',views.Uchatrply),
    path('deleteuser/<id>',views.deleteuser),
    path('deleteuserprofile/<id>',views.deleteuserprofile),
    path('myprogress',views.myprogress),
    path('myprogresstrainer/<id>',views.myprogresstrainer),

]